# Generated by Django 6.1 on 2026-08-28 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(help_text='Montant en FCFA')),
                ('method', models.CharField(choices=[('CASH', 'Espèces'), ('MTN', 'MTN Mobile Money'), ('ORANGE', 'Orange Money')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SUCCESS', 'Réussi'), ('FAILED', 'Échoué'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=20)),
                ('phone_number', models.CharField(blank=True, help_text='Numéro de téléphone pour paiement Mobile Money/Orange Money', max_length=20, null=True)),
                ('transaction_reference', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
