# Generated by Django 6.1 on 2026-08-28 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cni_number', models.CharField(blank=True, max_length=100, null=True)),
                ('cni_front', models.ImageField(blank=True, null=True, upload_to='verifications/clients/')),
                ('cni_back', models.ImageField(blank=True, null=True, upload_to='verifications/clients/')),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NON_SOUMIS', 'Non soumis'), ('EN_ATTENTE', 'En attente'), ('VALIDE', 'Valide'), ('REFUSE', 'Refusé'), ('EXPIRE', 'Expiré')], default='NON_SOUMIS', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Verification',
                'verbose_name_plural': 'Client Verifications',
            },
        ),
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cni_number', models.CharField(blank=True, max_length=100, null=True)),
                ('cni_front', models.ImageField(blank=True, null=True, upload_to='verifications/drivers/')),
                ('cni_back', models.ImageField(blank=True, null=True, upload_to='verifications/drivers/')),
                ('cni_expiry', models.DateField(blank=True, null=True)),
                ('license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('license_category', models.CharField(blank=True, max_length=50, null=True)),
                ('license_expiry', models.DateField(blank=True, null=True)),
                ('license_image', models.ImageField(blank=True, null=True, upload_to='verifications/drivers/licenses/')),
                ('status', models.CharField(choices=[('NON_SOUMIS', 'Non soumis'), ('EN_ATTENTE', 'En attente'), ('VALIDE', 'Valide'), ('REFUSE', 'Refusé'), ('EXPIRE', 'Expiré')], default='NON_SOUMIS', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Driver Profile',
                'verbose_name_plural': 'Driver Profiles',
            },
        ),
    ]
