# Generated by Django 6.1 on 2026-08-28 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientverification',
            options={'verbose_name': 'Vérification passager', 'verbose_name_plural': 'Vérifications passagers'},
        ),
        migrations.AlterModelOptions(
            name='driverprofile',
            options={'verbose_name': 'Profil chauffeur', 'verbose_name_plural': 'Profils chauffeurs'},
        ),
    ]
