# Generated by Django 6.1 on 2026-08-28 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-created_at'], 'verbose_name': 'Évaluation', 'verbose_name_plural': 'Évaluations'},
        ),
    ]
