# Generated by Django 6.1 on 2026-08-28 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': 'Véhicule', 'verbose_name_plural': 'Véhicules'},
        ),
        migrations.AlterModelOptions(
            name='vehicledocument',
            options={'verbose_name': 'Document de véhicule', 'verbose_name_plural': 'Documents de véhicule'},
        ),
    ]
