# Generated by Django 6.1 on 2026-08-28 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_places', models.PositiveSmallIntegerField()),
                ('prix_unitaire', models.PositiveIntegerField(help_text='Prix en FCFA')),
                ('montant_total', models.PositiveIntegerField(help_text='Montant total en FCFA')),
                ('statut', models.CharField(choices=[('PENDING', 'En attente'), ('CONFIRMED', 'Confirmée'), ('CANCELLED', 'Annulée'), ('REJECTED', 'Refusée'), ('COMPLETED', 'Terminée')], default='PENDING', max_length=20)),
                ('payment_method', models.CharField(choices=[('CASH', 'Espèces'), ('MTN', 'MTN Mobile Money'), ('ORANGE', 'Orange Money')], default='CASH', max_length=20)),
                ('payment_status', models.CharField(default='PENDING', max_length=20)),
                ('transaction_reference', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('trip_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='trips.tripoffer')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
