# Generated by Django 6.1 on 2026-08-28 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routes', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TripOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_depart', models.DateField()),
                ('heure_depart', models.TimeField()),
                ('places_totales', models.PositiveSmallIntegerField()),
                ('places_disponibles', models.PositiveSmallIntegerField()),
                ('prix_unitaire', models.PositiveIntegerField(help_text='Prix unitaire en FCFA')),
                ('statut', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('FULL', 'Full'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_offers', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='routes.route')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Trip Offer',
                'verbose_name_plural': 'Trip Offers',
                'ordering': ['-date_depart', '-heure_depart'],
            },
        ),
    ]
