# Generated by Django 6.1 on 2026-08-28 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tripoffer',
            options={'ordering': ['-date_depart', '-heure_depart'], 'verbose_name': 'Offre de trajet', 'verbose_name_plural': 'Offres de trajet'},
        ),
        migrations.AlterField(
            model_name='tripoffer',
            name='statut',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('PUBLISHED', 'Publié'), ('FULL', 'Complet'), ('CANCELLED', 'Annulé'), ('COMPLETED', 'Terminé')], default='DRAFT', max_length=20),
        ),
    ]
