# Generated by Django 6.1 on 2026-08-28 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('ACCOUNT_VERIFIED', 'Compte vérifié'), ('BOOKING_CONFIRMED', 'Réservation confirmée'), ('TRIP_STARTING', 'Trajet commençant bientôt'), ('BOOKING_CANCELLED', 'Réservation annulée'), ('DOCUMENT_EXPIRED', 'Document expiré'), ('NEW_RATING', 'Nouvelle évaluation reçue'), ('PAYMENT_RECEIVED', 'Paiement reçu'), ('OTHER', 'Autre')], default='OTHER', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
